### ISSUE TITLE
My PR is not merged yet, everything is fine in my PR still. Is it  biased ? ( As I don't have n number of stars or n number of followers)

### ISSUE THREAD

**Issue by SoumyaChoubey** [education/graduation#3545]

**Comment by aryanrawlani28** [comment]
@SoumyaChoubey Everything is fine, your PR will get merged eventually. Because there were more than 2000 PRs, the team will obviously take some time to review them all. 

The review process is not biased in any form, they're reviewing it in a random order to ensure this.

You can close this issue because eventually your PR will be reviewed and merged. (And no, it doesn't depend on any external factors like number of stars or followers)

Please be patient!
